import {StyleSheet} from 'react-native';
import {color} from 'react-native-reanimated';
import {Colors} from '../../global/colors';

const styles = StyleSheet.create({
  matchScheduleHeader: {
    flexDirection: 'row',
    width: '95%',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
  },
  onlineViews: {
    flexDirection: 'row',
    marginLeft: 'auto',
    alignItems: 'center',
  },
  matchStatus: {
    flexDirection: 'row',
    position: 'absolute',
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  matchInfo: {
    flexDirection: 'row',
    fontSize: 25,
  },
  matchScheduleContent: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '95%',
    justifyContent: 'center',
    marginLeft: 10,
    marginRight: 10,
    height: 45,
  },
  spaceBetween: {
    marginRight: 5,
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'PingFang SC',
    color: Colors.colorMatchTitle,
  },
  liveStatus: {
    color: 'red',
    marginRight: 5,
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'PingFang SC',
  },
  liveScore: {
    flexDirection: 'row',
    width: '30%',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  subscribeBtn: {
    flexDirection: 'row',
    width: '30%',
    justifyContent: 'center',
  },
  subscribeTouchable: {
    padding: 15,
  },
  scheduleFont: {
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'PingFang SC',
    marginBottom: 'auto',
    marginTop: 'auto',
  },
  scoreFont: {
    fontStyle: 'normal',
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'PingFang SC',
    paddingHorizontal: 5,
    color: 'black',
  },
  highScoreFont: {
    fontStyle: 'normal',
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'PingFang SC',
    paddingHorizontal: 5,
    color: Colors.colorLightOrange,
  },
  headerFont: {
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'PingFang SC',
    color: Colors.colorMatchTitle,
  },
  viewImage: {
    width: 15,
    height: 15,
  },
  streamerList: {
    alignItems: 'center',
    marginBottom: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '95%',
    justifyContent: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  liveStreamer: {
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'PingFang SC',
    textDecorationLine: 'underline',
    color: '#F09800',
    marginHorizontal: 5,
  },
  streamer: {
    fontStyle: 'normal',
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'PingFang SC',
    textDecorationLine: 'underline',
    color: '#B5B5B5',
    marginHorizontal: 5,
  },
  border: {
    borderTopWidth: 1,
    borderTopColor: Colors.colorLightGrey,
    height: 90,
  },
  teamContentA: {
    flexDirection: 'row',
    width: '25%',
    justifyContent: 'flex-end',
  },
  teamContentB: {
    flexDirection: 'row',
    width: '25%',
    justifyContent: 'flex-start',
  },
  teamImage: {
    height: 30,
    width: 30,
    marginLeft: 5,
    marginRight: 5,
    resizeMode: 'contain',
  },
  teamLogoText: {
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginTop: 'auto',
    color: 'white',
    fontSize: 18,
    fontFamily: '045-SSYiFeiTi',
  },
  liveIcon: {
    backgroundColor: 'red',
    width: 8,
    height: 8,
    borderRadius: 4,
    margin: 5,
  },
  subImage: {
    width: 15,
    height: 17,
    resizeMode: 'stretch',
  },
  liveType: {
    flexDirection: 'row',
    marginLeft: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
  },
  liveTypeImage: {
    width: 23,
    height: 15,
    marginRight: 5,
    right: 0,
  },
  matchScheduleFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
    height: 15,
    position: 'absolute',
    bottom: 0,
  },
  viewFooter: {
    height: 15,
    flexDirection: 'row',
    backgroundColor: '#FFA100',
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  footerFont: {
    fontStyle: 'normal',
    fontSize: 9,
    fontWeight: '600',
    fontFamily: 'PingFang SC',
    color: '#FFFFFF',
  },
  penaltyScore: {
    color: '#808080',
    fontFamily: 'PingFang SC',
    fontStyle: 'normal',
    fontSize: 11,
    fontWeight: '400',
  },
  penaltyWinScore: {
    color: '#FFA100',
    fontFamily: 'PingFang SC',
    fontStyle: 'normal',
    fontSize: 11,
    fontWeight: '400',
  },
});

export default styles;
